// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Relias.ContentLibraryService.Infra.Persistence;
using Relias.ContentLibraryService.Infra.Persistence.Migrations;

#nullable disable

namespace Relias.ContentLibraryService.Infra.Persistence.Migrations

{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240530113717_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Permission", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier")
                    .HasDefaultValueSql("(newid())");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("RoleId")
                   .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("Created")
                        .HasColumnType(nameof(DateTime));

                b.Property<string>("CreatedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("LastModified")
                    .HasColumnType(nameof(DateTime));

                b.Property<string>("LastModifiedBy")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Permissions");
            });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.ModuleCategory", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier")
                    .HasDefaultValueSql("(newid())");

                b.Property<DateTime>("Created")
                    .HasColumnType("datetime");

                b.Property<string>("CreatedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("LastModified")
                    .HasColumnType("datetime");

                b.Property<string>("LastModifiedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("ModuleCategory", (string)null);
            });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.ModuleType", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier")
                    .HasDefaultValueSql("(newid())");

                b.Property<DateTime>("Created")
                    .HasColumnType("datetime");

                b.Property<string>("CreatedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("LastModified")
                    .HasColumnType("datetime");

                b.Property<string>("LastModifiedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("ModuleCategoryId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("ModuleCategoryId");

                b.ToTable("ModuleType", (string)null);
            });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.ModuleType", b =>
            {
                b.HasOne("Relias.ContentLibraryService.Domain.ModuleCategory", "ModuleCategory")
                    .WithMany("ModuleTypes")
                    .HasForeignKey("ModuleCategoryId")
                    .IsRequired()
                    .HasConstraintName("FK_ModuleType_ModuleCategory");

                b.Navigation("ModuleCategory");
            });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.ModuleCategory", b =>
            {
                b.Navigation("ModuleTypes");
            });
#pragma warning restore 612, 618
        }
    }
}
