// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Relias.ContentLibraryService.Infra.Persistence;

#nullable disable

namespace Relias.ContentLibraryService.Infra.Persistence.Migrations


{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240711115731_Module_Organization_Schema")]
    partial class Module_Organization_Schema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Language", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("Created")
                        .HasColumnType("DateTime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("DateTime");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageId");

                    b.ToTable("Language", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Library.Library", b =>
                {
                    b.Property<Guid>("LibraryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("Created")
                        .HasColumnType("DateTime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("DateTime");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LibraryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LibraryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuleIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LibraryId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Library", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Module.Module", b =>
                {
                    b.Property<Guid>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("Created")
                        .HasColumnType("DateTime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("DateTime");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModuleStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("ModuleTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Version")
                        .HasColumnType("smallint");

                    b.HasKey("ModuleId");

                    b.HasIndex("ModuleTypeId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Module", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.ModuleCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("Created")
                        .HasColumnType("DateTime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("DateTime");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ModuleCategory", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.ModuleLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("Created")
                        .HasColumnType("DateTime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("DateTime");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ModuleId");

                    b.ToTable("ModuleLanguage", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.ModuleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("Created")
                        .HasColumnType("DateTime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("DateTime");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ModuleCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleCategoryId");

                    b.ToTable("ModuleType", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Organization.Organization", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("Created")
                        .HasColumnType("DateTime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("DateTime");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LegacyOrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("OrganizationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrganizationId");

                    b.ToTable("Organization", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Organization.OrganizationLibrary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("Created")
                        .HasColumnType("DateTime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("DateTime");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("OrganizationLibrary", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("Created")
                        .HasColumnType("DateTime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("DateTime");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Permission", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Library.Library", b =>
                {
                    b.HasOne("Relias.ContentLibraryService.Domain.Organization.Organization", "Organization")
                        .WithMany("Libraries")
                        .HasForeignKey("OrganizationId")
                        .IsRequired()
                        .HasConstraintName("FK_Library_Organization");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Module.Module", b =>
                {
                    b.HasOne("Relias.ContentLibraryService.Domain.ModuleType", "ModulType")
                        .WithMany("Modules")
                        .HasForeignKey("ModuleTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Module_ModuleType");

                    b.HasOne("Relias.ContentLibraryService.Domain.Organization.Organization", "Organization")
                        .WithMany("Modules")
                        .HasForeignKey("OrganizationId")
                        .IsRequired()
                        .HasConstraintName("FK_Module_Organization");

                    b.Navigation("ModulType");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.ModuleLanguage", b =>
                {
                    b.HasOne("Relias.ContentLibraryService.Domain.Language", "Language")
                        .WithMany("ModuleLanguages")
                        .HasForeignKey("LanguageId")
                        .IsRequired()
                        .HasConstraintName("FK_ModuleLanguage_Language");

                    b.HasOne("Relias.ContentLibraryService.Domain.Module.Module", "Module")
                        .WithMany("ModuleLanguages")
                        .HasForeignKey("ModuleId")
                        .IsRequired()
                        .HasConstraintName("FK_ModuleLanguage_Module");

                    b.Navigation("Language");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.ModuleType", b =>
                {
                    b.HasOne("Relias.ContentLibraryService.Domain.ModuleCategory", "ModuleCategory")
                        .WithMany("ModuleTypes")
                        .HasForeignKey("ModuleCategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_ModuleType_ModuleCategory");

                    b.Navigation("ModuleCategory");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Organization.OrganizationLibrary", b =>
                {
                    b.HasOne("Relias.ContentLibraryService.Domain.Library.Library", "Library")
                        .WithMany("OrganizationLibraries")
                        .HasForeignKey("LibraryId")
                        .IsRequired()
                        .HasConstraintName("FK_OrganizationLibrary_Library");

                    b.HasOne("Relias.ContentLibraryService.Domain.Organization.Organization", "Organization")
                        .WithMany("OrganizationLibraries")
                        .HasForeignKey("OrganizationId")
                        .IsRequired()
                        .HasConstraintName("FK_OrganizationLibrary_Organization");

                    b.Navigation("Library");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Language", b =>
                {
                    b.Navigation("ModuleLanguages");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Library.Library", b =>
                {
                    b.Navigation("OrganizationLibraries");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Module.Module", b =>
                {
                    b.Navigation("ModuleLanguages");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.ModuleCategory", b =>
                {
                    b.Navigation("ModuleTypes");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.ModuleType", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Organization.Organization", b =>
                {
                    b.Navigation("Libraries");

                    b.Navigation("Modules");

                    b.Navigation("OrganizationLibraries");
                });
#pragma warning restore 612, 618
        }
    }
}
