// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Relias.ContentLibraryService.Infra.Persistence;

#nullable disable

namespace Relias.ContentLibraryService.Infra.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PolicyTag", b =>
                {
                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("PolicyId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PolicyTag");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Certificate.Certificate", b =>
                {
                    b.Property<Guid>("CertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Board")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("CertificateStatusStatusId")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreditHours")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CertificateId");

                    b.HasIndex("CertificateStatusStatusId");

                    b.ToTable("Certificate", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Content.Content", b =>
                {
                    b.Property<Guid>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ContentTypeId")
                        .HasColumnType("int");

                    b.HasKey("ContentId");

                    b.HasIndex("ContentTypeId");

                    b.ToTable("Content");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.ContentType.ContentType", b =>
                {
                    b.Property<int>("ContentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContentTypeId"));

                    b.Property<string>("ContentTypeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContentTypeId");

                    b.ToTable("ContentType");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Course.Course", b =>
                {
                    b.Property<Guid>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveBy")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ArchiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BriefDescription")
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<string>("ContentCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ContentId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRelias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LanguageIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NextReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("PublishBy")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("StatusId")
                        .HasColumnType("tinyint");

                    b.Property<int?>("TimeToCompleteInMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CourseId");

                    b.HasIndex("ContentId")
                        .IsUnique();

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Course.ReliasCourse.CareSetting", b =>
                {
                    b.Property<int>("CareSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CareSettingId"));

                    b.Property<int>("QuickbaseRecordId")
                        .HasColumnType("int");

                    b.Property<string>("Setting")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CareSettingId");

                    b.ToTable("CareSetting", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Course.ReliasCourse.CommercialProductDisclaimer", b =>
                {
                    b.Property<int>("CommercialProductDisclaimerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommercialProductDisclaimerId"));

                    b.Property<string>("Disclaimer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommercialProductDisclaimerId");

                    b.ToTable("CommercialProductDisclaimer", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Course.ReliasCourse.CompletionRequirement", b =>
                {
                    b.Property<int>("CompletionRequirementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompletionRequirementId"));

                    b.Property<string>("Requirement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompletionRequirementId");

                    b.ToTable("CompletionRequirement", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Course.ReliasCourse.ContentDisclaimer", b =>
                {
                    b.Property<int>("ContentDisclaimerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContentDisclaimerId"));

                    b.Property<string>("Disclaimer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContentDisclaimerId");

                    b.ToTable("ContentDisclaimer", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Course.ReliasCourse.Contributor", b =>
                {
                    b.Property<int>("ContributorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContributorId"));

                    b.Property<int?>("ContributorIdNum")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisclosureStatement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAndCredentials")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ShortBio")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContributorId");

                    b.ToTable("Contributor", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Course.ReliasCourse.CourseCareSetting", b =>
                {
                    b.Property<int>("CourseCareSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseCareSettingId"));

                    b.Property<int>("CareSettingId")
                        .HasColumnType("int");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CourseCareSettingId");

                    b.HasIndex("CareSettingId");

                    b.HasIndex("CourseId", "CareSettingId")
                        .IsUnique();

                    b.ToTable("CourseCareSetting", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Course.ReliasCourse.CourseContributor", b =>
                {
                    b.Property<int>("CourseContributorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseContributorId"));

                    b.Property<int>("ContributorId")
                        .HasColumnType("int");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CourseContributorId");

                    b.HasIndex("ContributorId");

                    b.HasIndex("CourseId", "ContributorId")
                        .IsUnique();

                    b.ToTable("CourseContributor", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Course.ReliasCourse.CourseDisclosure", b =>
                {
                    b.Property<int>("CourseDisclosureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseDisclosureId"));

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisclosureId")
                        .HasColumnType("int");

                    b.HasKey("CourseDisclosureId");

                    b.HasIndex("DisclosureId");

                    b.HasIndex("CourseId", "DisclosureId")
                        .IsUnique();

                    b.ToTable("CourseDisclosure", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Course.ReliasCourse.CourseTargetAudience", b =>
                {
                    b.Property<int>("CourseTargetAudienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseTargetAudienceId"));

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TargetAudienceId")
                        .HasColumnType("int");

                    b.HasKey("CourseTargetAudienceId");

                    b.HasIndex("TargetAudienceId");

                    b.HasIndex("CourseId", "TargetAudienceId")
                        .IsUnique();

                    b.ToTable("CourseTargetAudience", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Course.ReliasCourse.CourseTrainingTopic", b =>
                {
                    b.Property<int>("CourseTrainingTopicsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseTrainingTopicsId"));

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrainingTopicId")
                        .HasColumnType("int");

                    b.HasKey("CourseTrainingTopicsId");

                    b.HasIndex("TrainingTopicId");

                    b.HasIndex("CourseId", "TrainingTopicId")
                        .IsUnique();

                    b.ToTable("CourseTrainingTopic", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Course.ReliasCourse.CulturalAwarenessStatement", b =>
                {
                    b.Property<int>("CulturalAwarenessStatementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CulturalAwarenessStatementId"));

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CulturalAwarenessStatementId");

                    b.ToTable("CulturalAwarenessStatement", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Course.ReliasCourse.Disclosure", b =>
                {
                    b.Property<int>("DisclosureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DisclosureId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("QuickbaseRecordId")
                        .HasColumnType("int");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DisclosureId");

                    b.ToTable("Disclosure", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Course.ReliasCourse.LearningObjective", b =>
                {
                    b.Property<int>("LearningObjectiveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LearningObjectiveId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuickbaseRecordId")
                        .HasColumnType("int");

                    b.HasKey("LearningObjectiveId");

                    b.HasIndex("CourseId");

                    b.ToTable("LearningObjective", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Course.ReliasCourse.ReliasCourseProperties", b =>
                {
                    b.Property<int>("ReliasCoursePropertiesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReliasCoursePropertiesId"));

                    b.Property<int?>("CommercialProductDisclaimerId")
                        .HasColumnType("int");

                    b.Property<int?>("CompletionRequirementId")
                        .HasColumnType("int");

                    b.Property<int?>("ContentDisclaimerId")
                        .HasColumnType("int");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CulturalAwarenessStatementId")
                        .HasColumnType("int");

                    b.Property<string>("Disclosure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RequestForAccommodationsId")
                        .HasColumnType("int");

                    b.HasKey("ReliasCoursePropertiesId");

                    b.HasIndex("CommercialProductDisclaimerId");

                    b.HasIndex("CompletionRequirementId");

                    b.HasIndex("ContentDisclaimerId");

                    b.HasIndex("CulturalAwarenessStatementId");

                    b.HasIndex("RequestForAccommodationsId");

                    b.ToTable("ReliasCourseProperties", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Course.ReliasCourse.RequestForAccommodations", b =>
                {
                    b.Property<int>("RequestForAccommodationsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestForAccommodationsId"));

                    b.Property<string>("Request")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestForAccommodationsId");

                    b.ToTable("RequestForAccommodations", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Course.ReliasCourse.TargetAudience", b =>
                {
                    b.Property<int>("TargetAudienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TargetAudienceId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuickbaseRecordId")
                        .HasColumnType("int");

                    b.HasKey("TargetAudienceId");

                    b.ToTable("TargetAudience", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Course.ReliasCourse.TrainingTopic", b =>
                {
                    b.Property<int>("TrainingTopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainingTopicId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("QuickbaseRecordId")
                        .HasColumnType("int");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrainingTopicId");

                    b.ToTable("TrainingTopic", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Course.ScheduledCourse", b =>
                {
                    b.Property<int>("ScheduledCourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduledCourseId"));

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ScheduledBy")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("ScheduledCourseId");

                    b.HasIndex("CourseId", "StatusId")
                        .IsUnique();

                    b.ToTable("ScheduledCourse", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Language.Language", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageId");

                    b.ToTable("Language", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Language.ModuleLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("Created")
                        .HasColumnType("DateTime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("DateTime");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ModuleId");

                    b.ToTable("ModuleLanguage", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Lesson.Lesson", b =>
                {
                    b.Property<Guid>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("Created")
                        .HasColumnType("DateTime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("DateTime");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LessonTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("StatusId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LessonId");

                    b.HasIndex("LessonTypeId");

                    b.HasIndex("StatusId");

                    b.ToTable("Lesson", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.LessonType.LessonType", b =>
                {
                    b.Property<Guid>("LessonTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("Created")
                        .HasColumnType("DateTime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("DateTime");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LessonTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LessonTypeId");

                    b.ToTable("LessonType", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Library.Library", b =>
                {
                    b.Property<Guid>("LibraryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("Created")
                        .HasColumnType("DateTime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("DateTime");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LibraryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LibraryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuleIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LibraryId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Library", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Module.Module", b =>
                {
                    b.Property<Guid>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("ArchiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BriefDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("DateTime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FirstPublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LanguageIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("DateTime");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastPublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModuleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ModuleTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SettingIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("StatusId")
                        .HasColumnType("tinyint");

                    b.Property<string>("TargetAudienceIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Version")
                        .HasColumnType("smallint");

                    b.HasKey("ModuleId");

                    b.HasIndex("ModuleTypeId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("StatusId");

                    b.ToTable("Module", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Module.ModuleCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("Created")
                        .HasColumnType("DateTime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("DateTime");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ModuleCategory", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Module.ModuleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("Created")
                        .HasColumnType("DateTime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("DateTime");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ModuleCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleCategoryId");

                    b.ToTable("ModuleType", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Organization.Organization", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("Created")
                        .HasColumnType("DateTime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("DateTime");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LegacyOrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("OrganizationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrganizationId");

                    b.ToTable("Organization", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Organization.OrganizationLibrary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("Created")
                        .HasColumnType("DateTime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("DateTime");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("OrganizationLibrary", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Permission.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("Created")
                        .HasColumnType("DateTime");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("DateTime");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Permission", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Policy.Policy", b =>
                {
                    b.Property<Guid>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<int>("OrgId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PolicyEventReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PolicyPublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subtopic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PolicyId");

                    b.HasIndex("ContentId")
                        .IsUnique();

                    b.ToTable("Policy");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.PolicyTag.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagId");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Setting.Setting", b =>
                {
                    b.Property<Guid>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SettingId");

                    b.ToTable("Setting", (string)null);
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Status.Status", b =>
                {
                    b.Property<byte>("StatusId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusId");

                    b.ToTable("Status", (string)null);
                });

            modelBuilder.Entity("PolicyTag", b =>
                {
                    b.HasOne("Relias.ContentLibraryService.Domain.Policy.Policy", null)
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Relias.ContentLibraryService.Domain.PolicyTag.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Certificate.Certificate", b =>
                {
                    b.HasOne("Relias.ContentLibraryService.Domain.Status.Status", "CertificateStatus")
                        .WithMany()
                        .HasForeignKey("CertificateStatusStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CertificateStatus");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Content.Content", b =>
                {
                    b.HasOne("Relias.ContentLibraryService.Domain.ContentType.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContentType");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Course.Course", b =>
                {
                    b.HasOne("Relias.ContentLibraryService.Domain.Content.Content", null)
                        .WithOne()
                        .HasForeignKey("Relias.ContentLibraryService.Domain.Course.Course", "ContentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Course.ReliasCourse.CourseCareSetting", b =>
                {
                    b.HasOne("Relias.ContentLibraryService.Domain.Course.ReliasCourse.CareSetting", "CareSetting")
                        .WithMany()
                        .HasForeignKey("CareSettingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Relias.ContentLibraryService.Domain.Course.ReliasCourse.ReliasCourseProperties", null)
                        .WithMany("CareSettings")
                        .HasForeignKey("CourseId")
                        .HasPrincipalKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareSetting");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Course.ReliasCourse.CourseContributor", b =>
                {
                    b.HasOne("Relias.ContentLibraryService.Domain.Course.ReliasCourse.Contributor", "Contributor")
                        .WithMany()
                        .HasForeignKey("ContributorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Relias.ContentLibraryService.Domain.Course.ReliasCourse.ReliasCourseProperties", null)
                        .WithMany("Contributors")
                        .HasForeignKey("CourseId")
                        .HasPrincipalKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contributor");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Course.ReliasCourse.CourseDisclosure", b =>
                {
                    b.HasOne("Relias.ContentLibraryService.Domain.Course.ReliasCourse.ReliasCourseProperties", null)
                        .WithMany("Disclosures")
                        .HasForeignKey("CourseId")
                        .HasPrincipalKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Relias.ContentLibraryService.Domain.Course.ReliasCourse.Disclosure", "Disclosure")
                        .WithMany()
                        .HasForeignKey("DisclosureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Disclosure");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Course.ReliasCourse.CourseTargetAudience", b =>
                {
                    b.HasOne("Relias.ContentLibraryService.Domain.Course.ReliasCourse.ReliasCourseProperties", null)
                        .WithMany("TargetAudiences")
                        .HasForeignKey("CourseId")
                        .HasPrincipalKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Relias.ContentLibraryService.Domain.Course.ReliasCourse.TargetAudience", "TargetAudience")
                        .WithMany()
                        .HasForeignKey("TargetAudienceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TargetAudience");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Course.ReliasCourse.CourseTrainingTopic", b =>
                {
                    b.HasOne("Relias.ContentLibraryService.Domain.Course.ReliasCourse.ReliasCourseProperties", null)
                        .WithMany("TrainingTopics")
                        .HasForeignKey("CourseId")
                        .HasPrincipalKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Relias.ContentLibraryService.Domain.Course.ReliasCourse.TrainingTopic", "TrainingTopic")
                        .WithMany()
                        .HasForeignKey("TrainingTopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TrainingTopic");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Course.ReliasCourse.LearningObjective", b =>
                {
                    b.HasOne("Relias.ContentLibraryService.Domain.Course.ReliasCourse.ReliasCourseProperties", null)
                        .WithMany("LearningObjectives")
                        .HasForeignKey("CourseId")
                        .HasPrincipalKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Course.ReliasCourse.ReliasCourseProperties", b =>
                {
                    b.HasOne("Relias.ContentLibraryService.Domain.Course.ReliasCourse.CommercialProductDisclaimer", "CommercialProductDisclaimer")
                        .WithMany()
                        .HasForeignKey("CommercialProductDisclaimerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Relias.ContentLibraryService.Domain.Course.ReliasCourse.CompletionRequirement", "CompletionRequirement")
                        .WithMany()
                        .HasForeignKey("CompletionRequirementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Relias.ContentLibraryService.Domain.Course.ReliasCourse.ContentDisclaimer", "ContentDisclaimer")
                        .WithMany()
                        .HasForeignKey("ContentDisclaimerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Relias.ContentLibraryService.Domain.Course.Course", null)
                        .WithOne("ReliasCourseProperties")
                        .HasForeignKey("Relias.ContentLibraryService.Domain.Course.ReliasCourse.ReliasCourseProperties", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Relias.ContentLibraryService.Domain.Course.ReliasCourse.CulturalAwarenessStatement", "CulturalAwarenessStatement")
                        .WithMany()
                        .HasForeignKey("CulturalAwarenessStatementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Relias.ContentLibraryService.Domain.Course.ReliasCourse.RequestForAccommodations", "RequestForAccommodations")
                        .WithMany()
                        .HasForeignKey("RequestForAccommodationsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CommercialProductDisclaimer");

                    b.Navigation("CompletionRequirement");

                    b.Navigation("ContentDisclaimer");

                    b.Navigation("CulturalAwarenessStatement");

                    b.Navigation("RequestForAccommodations");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Course.ScheduledCourse", b =>
                {
                    b.HasOne("Relias.ContentLibraryService.Domain.Course.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Language.ModuleLanguage", b =>
                {
                    b.HasOne("Relias.ContentLibraryService.Domain.Language.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Relias.ContentLibraryService.Domain.Module.Module", "Module")
                        .WithMany("ModuleLanguages")
                        .HasForeignKey("ModuleId")
                        .IsRequired()
                        .HasConstraintName("FK_ModuleLanguage_Module");

                    b.Navigation("Language");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Lesson.Lesson", b =>
                {
                    b.HasOne("Relias.ContentLibraryService.Domain.LessonType.LessonType", "LessonType")
                        .WithMany("Lessons")
                        .HasForeignKey("LessonTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Lesson_LessonType");

                    b.HasOne("Relias.ContentLibraryService.Domain.Status.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LessonType");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Library.Library", b =>
                {
                    b.HasOne("Relias.ContentLibraryService.Domain.Organization.Organization", "Organization")
                        .WithMany("Libraries")
                        .HasForeignKey("OrganizationId")
                        .IsRequired()
                        .HasConstraintName("FK_Library_Organization");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Module.Module", b =>
                {
                    b.HasOne("Relias.ContentLibraryService.Domain.Module.ModuleType", "ModuleType")
                        .WithMany("Modules")
                        .HasForeignKey("ModuleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Module_ModuleType");

                    b.HasOne("Relias.ContentLibraryService.Domain.Organization.Organization", "Organization")
                        .WithMany("Modules")
                        .HasForeignKey("OrganizationId")
                        .IsRequired()
                        .HasConstraintName("FK_Module_Organization");

                    b.HasOne("Relias.ContentLibraryService.Domain.Status.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModuleType");

                    b.Navigation("Organization");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Module.ModuleType", b =>
                {
                    b.HasOne("Relias.ContentLibraryService.Domain.Module.ModuleCategory", "ModuleCategory")
                        .WithMany("ModuleTypes")
                        .HasForeignKey("ModuleCategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_ModuleType_ModuleCategory");

                    b.Navigation("ModuleCategory");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Organization.OrganizationLibrary", b =>
                {
                    b.HasOne("Relias.ContentLibraryService.Domain.Library.Library", "Library")
                        .WithMany("OrganizationLibraries")
                        .HasForeignKey("LibraryId")
                        .IsRequired()
                        .HasConstraintName("FK_OrganizationLibrary_Library");

                    b.HasOne("Relias.ContentLibraryService.Domain.Organization.Organization", "Organization")
                        .WithMany("OrganizationLibraries")
                        .HasForeignKey("OrganizationId")
                        .IsRequired()
                        .HasConstraintName("FK_OrganizationLibrary_Organization");

                    b.Navigation("Library");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Policy.Policy", b =>
                {
                    b.HasOne("Relias.ContentLibraryService.Domain.Content.Content", null)
                        .WithOne()
                        .HasForeignKey("Relias.ContentLibraryService.Domain.Policy.Policy", "ContentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Course.Course", b =>
                {
                    b.Navigation("ReliasCourseProperties");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Course.ReliasCourse.ReliasCourseProperties", b =>
                {
                    b.Navigation("CareSettings");

                    b.Navigation("Contributors");

                    b.Navigation("Disclosures");

                    b.Navigation("LearningObjectives");

                    b.Navigation("TargetAudiences");

                    b.Navigation("TrainingTopics");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.LessonType.LessonType", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Library.Library", b =>
                {
                    b.Navigation("OrganizationLibraries");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Module.Module", b =>
                {
                    b.Navigation("ModuleLanguages");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Module.ModuleCategory", b =>
                {
                    b.Navigation("ModuleTypes");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Module.ModuleType", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("Relias.ContentLibraryService.Domain.Organization.Organization", b =>
                {
                    b.Navigation("Libraries");

                    b.Navigation("Modules");

                    b.Navigation("OrganizationLibraries");
                });
#pragma warning restore 612, 618
        }
    }
}
